### PR TITLE
Use cases from Disney

### PR DESCRIPTION
**Pull request by j0j0r0**
I've added some of the use cases that we've identified on the Disney Private Blockchain Platform team.

### CODE REVIEW

**Comment by mountielee** [comment]
will check merge permission for this pull request.

**Comment by j0j0r0** [comment]
It looks like the standards doc changes were merged, but not
the use cases file (applications).

On Sun, May 22, 2016 at 2:24 AM, Mountie Lee notifications@github.com
wrote:

> will check merge permission for this pull request.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/blockchain/pull/6#issuecomment-220822555

## 

j03
joe@createtank.com
voice +1 646 355 8865

**Comment by dazzaji** [comment]
Just confirming whether this is the version of the file you want: https://github.com/j0j0r0/blockchain/blob/da39a3cd64bf5ae5e7bd72275eac521b90c4823b/application-areas.md

**Comment by j0j0r0** [comment]
Yes, that is the one.

Thank you!

On Mon, May 23, 2016 at 11:40 AM, Dazza Greenwood notifications@github.com
wrote:

> Just confirming whether this is the version of the file you want:
> https://github.com/j0j0r0/blockchain/blob/da39a3cd64bf5ae5e7bd72275eac521b90c4823b/application-areas.md
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/w3c/blockchain/pull/6#issuecomment-221052274

## 

j03
joe@createtank.com
voice +1 646 355 8865

**Pull request merged**
